//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void setup(); \
	void loop(); \
	bool deleteSMS(uint8_t index); \
	bool delete_all_SMS(); \
	void node_push(stack_t *s, const char* cmd, char *d, const char *t); \
	void smsInit(); \
	bool checkNetwork(); \
	bool initModem(); \

