//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void setup(); \
	void loop(); \
	bool delete_SMS(uint8_t index); \
	bool delete_all_SMS(); \
	void write_Mode(uint8_t mode_number); \
	void smsInit(); \
	bool checkNetwork(); \
	bool initModem(); \

